controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_send_sms:
    path: /send-sms/{to}/{from}/{message}
    controller: App\Controller\SendSmsController::index